name: PyPI deploy

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  pypi-deploy:
    name: Deploying Python Package
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/epmatools
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
          # setuptools_scm requires a non-shallow clone of the repository
          fetch-depth: 0

    - uses: actions/setup-python@v5
      name: Install Python

    - name: Build SDist
      run: pipx run build --sdist

    - uses: pypa/gh-action-pypi-publish@release/v1

